### ISSUE TITLE
Minvolume of 0 turns off speaker permanently

### ISSUE THREAD

**Issue by probabble** [probabble/roundware-server#2]
If I have the minvolume for a speaker set to 0.0 (which is a typical setting), and if I move the listener outside of the speaker's range, the volume goes to 0.0 as desired, but then when I move the listener back into range, the volume does not go back up at all.

The logs suggest that once the volume on a speaker hits 0.0, that speaker is turned off such that it is ignored even when the listener comes back in range. 

If, however, I set the minvolume to something approaching 0.0, but not quite 0.0, such as 0.0001, all works fine. This is an easy workaround, but obviously, it should not require this.

from comment by @hburgund

**Comment by hburgund** [comment]
First the good news: the updates to the data migration seems to be working properly.

But otherwise, some stuff is slightly improved, but still not working fully. As best I can tell, when the listener moves out of range of a speaker, that speaker is no longer considered for the mixing and then when the listener moves back into range, the good news is that the speaker is again recognized (at least according to the logs). But, despite being recognized, the volume of the speaker doesn’t fade back in to where it should be i.e. the speaker volume isn’t actually calculated despite being recognized. 

Seems just like `calculate_volume` isn’t being called at all or not at the proper time perhaps? The logs don't contain any of the statements that `calculate_volume` typically prints, so I am pretty sure that function isn't being run for the newly re-entered speaker. It seems to be run for speakers that were never removed (i.e. volume reaches 0), so my best guess is that somehow the newly re-entered speaker isn't being included in the array that's being sent to `calculate_volume`. 

I flailed about a bit in the code to see if I could figure it out, but this part of the codebase is pretty new to me. I have been focussed on the `move_listener` code in `gpsmixer.py`, but I don't really understand it with all the loops and whatnot, so I'm hoping you could walk me through it sometime as I'm sure it would help debugging.

I tried to test things with multiple speakers to try to glean more info on the current behavior, but it just got vastly more difficult to interpret. We need to get a single speaker situation working where the speaker is removed and then re-added with proper volume recalculation and then I can test more speaker situations.

**Comment by hburgund** [comment]
another issue with widespread and not totally conclusive causes; fixed by 62625ec7756f03dea707d7c400d93bcd2e77632d and previous commits

**Comment by probabble** [comment]
fixed.
